export const content = {
  name: { first: 'Gopikrishnan', last: 'Balagopal' },
  tagline: 'Full-stack developer · Kerala, India',
  intro: 'I turn messy product problems into features that just work. Currently building at Cooee.',
  bio: "23, based in Kerala. I'm a full-stack engineer at Cooee, working across calling, payments and customer support — mostly Go on the backend and React on the front. I like owning a feature from the first API question to the deploy.",
  email: 'gopikrishnanb2003@gmail.com',
  github: 'https://github.com/Gopi-krishnan-77',
  linkedin: 'https://linkedin.com/in/gopikrishnanbalagopal',

  experience: [
    {
      company: 'Cooee',
      role: 'Graduate Software Engineer · Full Stack',
      period: 'Sept 2025 – Present',
      current: true,
      bullets: [
        'Own the Cooee Business web app — onboarding, team management, usage dashboards and payments — from first prototype to live deploy',
        'Led the move to a new customer support platform end to end — backend, web app, ticket migration and cutover — with a one-switch rollback if anything goes wrong',
        'Built in-app support chat with real-time updates, plus agent tooling that puts a customer\'s account and call history in front of support, so issues get resolved faster',
        'Built calling features — international calling over WebRTC, call forwarding, subscriptions and auto top-ups',
        'Own major frontend modules in React, Next.js, Tailwind and Firebase',
        'Led the marketing site move from WordPress to Next.js with a headless CMS, country-specific pages, SEO improvements and GA4 tracking',
      ],
    },
    {
      company: 'Benfi Consultants Pte Ltd',
      role: 'Software Developer Intern',
      period: 'Jul 2024 – Nov 2024',
      current: false,
      bullets: [
        'Built and optimised backend APIs using Django for internal business intelligence workflows',
        'Evaluated LLMs (Qwen series) for automating analytics and reporting workflows',
        'Contributed to early prototypes of an AI-driven home assistant',
      ],
    },
  ],

  projects: [
    {
      id: 'callcheck',
      title: 'CallCheck',
      subtitle: 'Is your network ready for VoIP?',
      description: 'A free in-browser tool that tests latency, jitter, packet loss and MOS score. Built from real WebRTC experience at Cooee.',
      metrics: [
        { label: 'Latency', value: 24, suffix: 'ms', decimals: 0 },
        { label: 'Jitter', value: 3.2, suffix: 'ms', decimals: 1 },
        { label: 'Packet Loss', value: 0.4, suffix: '%', decimals: 1 },
        { label: 'MOS Score', value: 4.5, suffix: '', decimals: 1 },
      ],
      stack: ['Next.js', 'TypeScript', 'Go'],
      github: 'https://github.com/Gopi-krishnan-77/callcheck',
      cta: { label: 'Visit site →', href: 'https://callcheck.gopikrishnanb.co.in' },
    },
    {
      id: 'draftarena',
      title: 'Draft Arena',
      subtitle: 'Pick your XI. Settle the debate.',
      description: 'A head-to-head football drafting game. Two managers snake-draft an all-time XI, on one phone or live online, and an AI judges both squads and calls a winner.',
      highlights: ['Live rooms with a 60s pick clock', 'Draft rules enforced in Postgres', 'AI verdict in four personalities'],
      stack: ['Next.js', 'TypeScript', 'Supabase', 'Postgres', 'OpenRouter'],
      github: 'https://github.com/Gopi-krishnan-77/Draft-arena',
      cta: { label: 'Play →', href: 'https://draft.gopikrishnanb.co.in' },
    },
    {
      id: 'decarb',
      title: 'DeCarb',
      subtitle: 'Carbon credit marketplace',
      description: 'Decentralised platform for transparent carbon credit trading. Web3Auth wallet onboarding, Razorpay fiat payments, Toucan-based retirement certificates.',
      awards: ['Finalist — SIGHT 2.0', 'Runner-up — BlockHash LIVE'],
      stack: ['Next.js', 'Solidity', 'Web3Auth', 'Razorpay'],
      github: 'https://github.com/DeCarb-Marketplace',
    },
    {
      id: 'tedx',
      title: 'TEDx Saintgits',
      description: 'Official event site with ticketing.',
      stack: ['Next.js', 'Firebase'],
      github: 'https://github.com/basilrari/tedxsaintgits',
      earlier: true,
    },
    {
      id: 'alerteye',
      title: 'AlertEye',
      description: 'Real-time driver drowsiness detection from facial landmarks.',
      stack: ['Python', 'OpenCV'],
      github: 'https://github.com/Gopi-krishnan-77/Alert-Eye',
      earlier: true,
    },
    {
      id: 'edufinease',
      title: 'EduFinEase',
      description: 'Fee tracking, payments and reports for schools and colleges.',
      stack: ['React', 'Node.js', 'Firebase'],
      github: 'https://github.com/EduFinEase',
      earlier: true,
    },
    {
      id: 'deex3',
      title: 'DeEx3 DAO',
      description: 'A DAO where researchers publish and peer-review work on-chain.',
      stack: ['Solidity', 'React', 'IPFS'],
      github: 'https://github.com/orgs/DeEx3-DAO/repositories',
      earlier: true,
    },
  ],

  stack: [
    { group: 'Languages', items: ['Go', 'TypeScript', 'JavaScript', 'Python', 'Solidity'] },
    { group: 'Frontend', items: ['React', 'Next.js', 'Redux', 'TanStack Query', 'Tailwind CSS'] },
    { group: 'Backend & data', items: ['Django', 'Express.js', 'PostgreSQL', 'WebSockets', 'WebRTC', 'BigQuery'] },
    { group: 'Platforms', items: ['Firebase', 'Auth0', 'Stripe', 'AWS Amplify', 'Cloudflare Workers', 'Sanity CMS', 'GA4'] },
  ],

  awards: [
    {
      kind: 'Hackathon',
      title: 'Runner-up — Web3 for India 2030 Ideathon',
      sub: 'BlockHash LIVE, Kerala Blockchain Academy',
      year: '2023',
    },
    {
      kind: 'Hackathon',
      title: 'Finalist — SIGHT 2.0',
      sub: 'UST Global Hackathon',
      year: '2024',
    },
    {
      kind: 'Research',
      title: 'Research Publication — "Security in Metaverse"',
      sub: 'Springer CCIS, ICAISM',
      year: '2025',
    },
    {
      kind: 'Hackathon',
      title: 'Project Showcase — ETHIndia',
      sub: 'India\'s biggest Ethereum hackathon',
      year: '2023',
    },
    {
      kind: 'Programme',
      title: 'Industrial Trainee — Intel Unnati',
      sub: 'Intel industry-academia programme',
      year: '2023',
    },
    {
      kind: 'Leadership',
      title: 'Treasurer — EXCEL Saintgits',
      sub: 'Student technical association · budgets and event operations',
      year: '2024–25',
    },
    {
      kind: 'College',
      title: 'Special Recognition Award',
      sub: 'Saintgits CSE Department — outstanding contributions',
      year: '2025',
    },
    {
      kind: 'Sport',
      title: 'Captain — Saintgits College Cricket Team',
      sub: 'Led team to inter-college tournaments',
      year: '2024–25',
    },
  ],
}
